name: MilkMines
main: site.ichocomilk.mines.MinesPlugin
version: 1.2
author: iChocoMilk
api-version: 1.21

softdepend: ["PlaceholderAPI"]

commands:
  mines:
    description: "Mines command"
    aliases: ["mine"]